# Generated by Django 5.0.2 on 2024-05-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='boylam',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='enlem',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
